### ISSUE TITLE
IPv6 Address with boot parameter

### ISSUE THREAD

**Issue by genofire** [grazzolini/mkinitcpio-netconf#10]

**Comment by grazzolini** [comment]
@genofire is this issue still relevant for you? Because the current implementation of ipconfig can't handle with ipv6, as far as I can tell. But, ipv6 should work out of the box through slaac, as soon as the interface is brought up. So, you can configure netconf to simply bring the interface up through dhcp.

**Comment by genofire** [comment]
Jep, but i solve it by:
```bash
sed -i 's/netconf/netconf ipaddress)/' /mnt/etc/mkinitcpio.conf

cat > /etc/initcpio/install/ipaddress <<MAINEOF
build ()
{
	add_runscript
}
help ()
{
cat<<HELPEOF
	Sets a route to a gateway which is not in our subnet.
HELPEOF
}
MAINEOF

cat > /etc/initcpio/hooks/ipaddress <<MAINEOF
run_hook ()
{
	ip l set up eth0
	ip -6 a add 2a01:4f8:151:1422::40/80 dev eth0
	ip -6 r add default via 2a01:4f8:151:1422::2 dev eth0
}
MAINEOF
```

**Comment by grazzolini** [comment]
@genofire I'm looking into using busybox's own implementation of this.

**Comment by genofire** [comment]
Keep me informat
